[protocol]
name = "hydrazoa-collat"
scope = ""
version = "0.0.0"
description = ""
main = "main.tx3"

[registry]
url = "https://tx3.land"

[profiles.devnet]
chain = "CardanoDevnet"

[profiles.preview]
chain = "CardanoPreview"

[profiles.preprod]
chain = "CardanoPreprod"

[profiles.mainnet]
chain = "CardanoMainnet"

[[bindings]]
output_dir = "./src"

[bindings.template]
repo = "tx3-lang/rust-sdk"
path = ".trix/client-lib"
ref = "bindgen-v1alpha2"

[[wallets]]
name = "faucet"
random_key = true
